[package]
authors = ['Anonymous']
edition = '2018'
name = 'pallet-dotmogbase'
version = "2.0.0"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet dmog for defining custom runtime logic."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# third-party dependencies
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }

# primitives
sp-runtime = { version = "3.0.0", default-features = false, path = "../../../../primitives/runtime" }
sp-std = { version = "3.0.0", default-features = false, path = "../../../../primitives/std" }
sp-core = { version = "3.0.0", default-features = false, path = "../../../../primitives/core" }
node-primitives = { version = "2.0.0", default-features = false, path = "../../primitives" }

# frame dependencies
frame-support = { version = "3.0.0", default-features = false, path = "../../../../frame/support" }
frame-system = { version = "3.0.0", default-features = false, path = "../../../../frame/system" }

[dev-dependencies]
sp-io = { version = "3.0.0", path = "../../../../primitives/io" }

[features]
default = ['std']
std = [
	'serde',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
    'sp-core/std',
]
